export const SCENES = [
  {
    id: 'main-cardioid',
    mode: 'mandelbrot',
    power: 2,
    center: { x: -0.5, y: 0.0 },
    zoom: 0.22,
    lockCenter: true,
  },
  {
    id: 'full-set',
    mode: 'mandelbrot',
    power: 2,
    center: { x: -0.5, y: 0.0 },
    zoom: 0.14,
  },
  {
    id: 'deep-space',
    mode: 'mandelbrot',
    power: 2,
    center: { x: -0.5, y: 0.0 },
    zoom: 0.12,
  },
  {
    id: 'mini-mandel',
    mode: 'mandelbrot',
    power: 2,
    center: { x: -1.775, y: 0.0 },
    zoom: 5,
  },
  {
    id: 'antennae',
    mode: 'mandelbrot',
    power: 2,
    center: { x: -0.16, y: 1.0405 },
    zoom: 3,
  },
  {
    id: 'tendrils',
    mode: 'julia',
    c: { cr: -0.7269, ci: 0.1889 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.35,
  },
  {
    id: 'tendrils-soft',
    mode: 'julia',
    c: { cr: -0.7269, ci: 0.1889 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.35,
  },
  {
    id: 'rabbit',
    mode: 'julia',
    c: { cr: -0.123, ci: 0.745 },
    center: { x: 0.0, y: 0.25 },
    zoom: 0.25,
  },
  {
    id: 'rabbit-soft',
    mode: 'julia',
    c: { cr: -0.123, ci: 0.745 },
    center: { x: -0.05, y: 0.4 },
    zoom: 0.45,
  },
  {
    id: 'siegel',
    mode: 'julia',
    c: { cr: -0.39054, ci: -0.58679 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.35,
  },
  {
    id: 'dendrite',
    mode: 'julia',
    c: { cr: -0.7, ci: 0.27015 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.3,
  },
  {
    id: 'feather',
    mode: 'julia',
    c: { cr: -0.835, ci: -0.2321 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.45,
  },
  {
    id: 'galaxy',
    mode: 'julia',
    c: { cr: -0.4, ci: 0.6 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.22,
  },
  {
    id: 'frost',
    mode: 'julia',
    c: { cr: -0.8, ci: 0.156 },
    center: { x: 0.0, y: 0.0 },
    zoom: 0.22,
  },
  {
    id: 'newton-3',
    mode: 'newton',
    newtonPower: 3,
    relaxation: 1.0,
    center: { x: 0.0, y: 0.0 },
    zoom: 0.25,
    lockCenter: true,
  },
  {
    id: 'newton-5',
    mode: 'newton',
    newtonPower: 5,
    relaxation: 1.05,
    center: { x: 0.0, y: 0.0 },
    zoom: 0.25,
    lockCenter: true,
  },
  {
    id: 'newton-wild',
    mode: 'newton',
    newtonPower: 3,
    relaxation: 1.1,
    center: { x: 0.0, y: 0.0 },
    zoom: 0.3,
    lockCenter: true,
  },
  {
    id: 'newton-8',
    mode: 'newton',
    newtonPower: 8,
    relaxation: 1.0,
    center: { x: 0.0, y: 0.0 },
    zoom: 0.22,
    lockCenter: true,
  },
];